# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  paths:
    include:
      - resources/SupportingFiles/react-rating-ui-ts/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  workingDirectory: $(Build.SourcesDirectory)/resources/SupportingFiles/react-rating-ui-ts
  publishPath: '$(Build.ArtifactStagingDirectory)/s/resources/SupportingFiles/react-rating-ui-ts/build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: $(workingDirectory)

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.BuildDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(publishPath)'
    ArtifactName: 'drop'
