# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - resources/coaches/solutions/c#/Alerting_and_Notification

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  projects: '**/AlertingAndNotification.csproj'
  workingDirectory: $(Build.SourcesDirectory)/resources/coaches/solutions/c#/Alerting_and_Notification

steps:
  - template: 'CI-pipeline-solution-csharp-template.yml'