# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - resources/coaches/solutions/c#/PubSub_and_Network_Integration/process-receipts

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: "Release"
  projects: "**/process-receipts.csproj"
  workingDirectory: $(Build.SourcesDirectory)/resources/coaches/solutions/c#/PubSub_and_Network_Integration/process-receipts

steps:
  - template: "CI-pipeline-solution-csharp-template.yml"
