# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  paths:
    include:
      - resources/SupportingFiles/ExistingFunctions/User/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  workingDirectory: $(Build.SourcesDirectory)/resources/SupportingFiles/ExistingFunctions/User
  publishPath: '$(Build.ArtifactStagingDirectory)/User.zip'
  projectPath: '**/*User.csproj'

steps:
- script: dotnet restore
  displayName: 'dotnet restore'
  workingDirectory: '$(workingDirectory)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: '$(workingDirectory)'
  
- script: dotnet test
  displayName: 'dotnet test'
  workingDirectory: '$(workingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.BuildDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: DotNetCoreCLI@2
  displayName: dotnet publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(projectPath)'
    workingDirectory: '$(workingDirectory)'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(publishPath)'